<div class="container">
<?php foreach ($this->view->dados as $indice => $produto) { ?>
<div class="card-deck mb-3 text-center">
        <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal"><?= $produto['descricao'] ?></h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title">R$ <?= $produto['preco'] ?></h1>
          </div>
        </div>
<?php } ?>

</div>
